## Create an expression that concatenates the string "Python is " with the string "awesome!", and display the result:

In [ ]:
"Python is " + "awesome!"

'Python is awesome!'

## With a single Python expression, divide 17 by 3 using integer division, then square the result:

In [ ]:
(17 // 3) ** 2

25

## On two distinct lines of a single Colab notebook cell, calculate the sum of 7 and 3, followed by the product of 5 and 4. The cell should output only display the result of the *second* expression (20).

In [ ]:
7 + 3
5 * 4

20

## In a *single* cell of a Colab notebook, demonstrate the difference between multiplying the number 5 by 3 and multiplying the string "5" by 3. Running the cell should result in **two** distinct results being displayed: 15 and 555.

In [ ]:
print(5 * 3)
'5' * 3

15

'555'

## Write a single line of code that performs the following operations in order: 10 plus 5, multiplied by 2, raised to the power of 2, and then integer-divided by 17:

In [ ]:
(((10 + 5) * 2) ** 2) // 17

52