## Setup

In [ ]:
import pandas as pd

In [ ]:
house_path = 'YOUR PATH HERE'

In [ ]:
house_sales = pd.read_csv(house_path)
house_sales.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

## Replace the following list of values in the "bathrooms" column of the house sales dataset, with the nearest whole numbers:

`[1.25,2.25,3.25,4.25,5.25,6.25]`

In [ ]:
house_sales['bathrooms'].value_counts().sort_index()

bathrooms
0.00      10
0.50       4
0.75      72
1.00    3852
1.25       9
1.50    1446
1.75    3048
2.00    1930
2.25    2047
2.50    5380
2.75    1185
3.00     753
3.25     589
3.50     731
3.75     155
4.00     136
4.25      79
4.50     100
4.75      23
5.00      21
5.25      13
5.50      10
5.75       4
6.00       6
6.25       2
6.50       2
6.75       2
7.50       1
7.75       1
8.00       2
Name: count, dtype: int64

In [ ]:
house_sales['bathrooms'] = house_sales['bathrooms'].replace([1.25,2.25,3.25,4.25,5.25,6.25], [1,2,3,4,5,6])

In [ ]:
house_sales['bathrooms'].value_counts().sort_index()

bathrooms
0.00      10
0.50       4
0.75      72
1.00    3861
1.50    1446
1.75    3048
2.00    3977
2.50    5380
2.75    1185
3.00    1342
3.50     731
3.75     155
4.00     215
4.50     100
4.75      23
5.00      34
5.50      10
5.75       4
6.00       8
6.50       2
6.75       2
7.50       1
7.75       1
8.00       2
Name: count, dtype: int64