In [ ]:
import pandas as pd

In [ ]:
ufos_path = 'YOUR PATH HERE'

In [ ]:
ufo_sightings = pd.read_csv(ufos_path)
ufo_sightings.head()

<ipython-input-16-87ccc3a49ac9>:1: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  ufo_sightings = pd.read_csv(ufos_path)

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611

In [ ]:
ufo_sightings.sum()

TypeError: can only concatenate str (not "int") to str

In [ ]:
ufo_sightings.sum(numeric_only=True)

longitude    -6.970639e+06
dtype: float64

In [ ]:
ufo_sightings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80332 entries, 0 to 80331
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              80332 non-null  object
 1   city                  80332 non-null  object
 2   state                 74535 non-null  object
 3   country               70662 non-null  object
 4   shape                 78400 non-null  object
 5   duration (seconds)    80332 non-null  object
 6   duration (hours/min)  80332 non-null  object
 7   comments              80317 non-null  object
 8   date posted           80332 non-null  object
 9   latitude              80332 non-null  object
 10  longitude             80332 non-null  float64
dtypes: float64(1), object(10)
memory usage: 6.7+ MB

In [ ]:
ufo_sightings['duration (seconds)'] = pd.to_numeric(ufo_sightings['duration (seconds)'],errors='coerce')
ufo_sightings['latitude'] = pd.to_numeric(ufo_sightings['latitude'],errors='coerce')

In [ ]:
ufo_sightings.sum(numeric_only=True)

duration (seconds)    7.243447e+08
latitude              3.062577e+06
longitude            -6.970639e+06
dtype: float64

In [ ]:
ufo_data = ufo_sightings.sum(numeric_only=True)

In [ ]:
type(ufo_data)

pandas.core.series.Series

In [ ]:
ufo_data

duration (seconds)    7.243447e+08
latitude              3.062577e+06
longitude            -6.970639e+06
dtype: float64

In [ ]:
ufo_sightings['duration (seconds)'].sum()

724344717.961