In [ ]:
import pandas as pd
pd.options.display.float_format = '{:.1f}'.format

In [ ]:
ufos_path = 'YOUR PATH HERE'

In [ ]:
ufo_sightings = pd.read_csv(ufos_path)

<ipython-input-4-195439c6c744>:1: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  ufo_sightings = pd.read_csv(ufos_path)

In [ ]:
ufo_sightings['datetime'] = pd.to_datetime(ufo_sightings['datetime'],errors='coerce')
ufo_sightings['duration (seconds)'] = pd.to_numeric(ufo_sightings['duration (seconds)'],errors='coerce')
ufo_sightings['date posted'] = pd.to_datetime(ufo_sightings['date posted'],errors='coerce')
ufo_sightings['latitude'] = pd.to_numeric(ufo_sightings['latitude'],errors='coerce')

In [ ]:
ufo_sightings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80332 entries, 0 to 80331
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              79638 non-null  datetime64[ns]
 1   city                  80332 non-null  object
 2   state                 74535 non-null  object
 3   country               70662 non-null  object
 4   shape                 78400 non-null  object
 5   duration (seconds)    80329 non-null  float64
 6   duration (hours/min)  80332 non-null  object
 7   comments              80317 non-null  object
 8   date posted           80332 non-null  datetime64[ns]
 9   latitude              80331 non-null  float64
 10  longitude             80332 non-null  float64
dtypes: datetime64[ns](2), float64(3), object(6)
memory usage: 6.7+ MB

In [ ]:
ufo_sightings.describe(include='all')

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
count,79638,80332,74535,70662,78400,80329.0,80332,80317,80332,80331.0,80332.0
unique,NaN,19900,67,5,29,NaN,8349,79997,NaN,NaN,NaN
top,NaN,seattle,ca,us,light,NaN,5 minutes,Fireball,NaN,NaN,NaN
freq,NaN,525,9655,65114,16565,NaN,4716,11,NaN,NaN,NaN
mean,2004-06-02 04:11:35.377081344,NaN,NaN,NaN,NaN,9017.2,NaN,NaN,2007-07-28 02:15:17.074142464,38.1,-86.8
min,1906-11-11 00:00:00,NaN,NaN,NaN,NaN,0.0,NaN,NaN,1998-03-07 00:00:00,-82.9,-176.7
25%,2001-08-11 23:07:30,NaN,NaN,NaN,NaN,30.0,NaN,NaN,2003-11-26 00:00:00,34.1,-112.1
50%,2006-11-28 08:18:30,NaN,NaN,NaN,NaN,180.0,NaN,NaN,2007-11-28 00:00:00,39.4,-87.9
75%,2011-06-25 23:23:45,NaN,NaN,NaN,NaN,600.0,NaN,NaN,2011-10-10 00:00:00,42.8,-78.8
max,2014-05-08 18:45:00,NaN,NaN,NaN,NaN,97836000.0,NaN,NaN,2014-05-08 00:00:00,72.7,178.4
std,NaN,NaN,NaN,NaN,NaN,620228.4,NaN,NaN,NaN,10.5,39.7