In [ ]:
import pandas as pd
pd.options.display.float_format = '{:.1f}'.format

In [ ]:
ufos_path = 'YOUR PATH HERE'

In [ ]:
ufo_sightings = pd.read_csv(ufos_path)
ufo_sightings.head()

<ipython-input-7-87ccc3a49ac9>:1: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  ufo_sightings = pd.read_csv(ufos_path)

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.9
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.6
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.9
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.6
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.8

In [ ]:
ufo_sightings['country'].value_counts()

country
us    65114
ca     3000
gb     1905
au      538
de      105
Name: count, dtype: int64

In [ ]:
updated_countries = ufo_sightings['country'].replace('de', 'germany')

In [ ]:
updated_countries.value_counts()

country
us         65114
ca          3000
gb          1905
au           538
germany      105
Name: count, dtype: int64

In [ ]:
old_country_names = ['us','ca','gb','au', 'de']
new_country_names = ['united states','canada','great britain','australia','germany']

updated_countries = ufo_sightings['country'].replace(old_country_names, new_country_names)

In [ ]:
updated_countries.value_counts()

country
united states    65114
canada            3000
great britain     1905
australia          538
germany            105
Name: count, dtype: int64

In [ ]:
ufo_sightings['country'] = updated_countries

In [ ]:
ufo_sightings.head(10)

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,united states,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.9
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.6
2,10/10/1955 17:00,chester (uk/england),NaN,great britain,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.9
3,10/10/1956 21:00,edna,tx,united states,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.6
4,10/10/1960 20:00,kaneohe,hi,united states,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.8
5,10/10/1961 19:00,bristol,tn,united states,sphere,300,5 minutes,My father is now 89 my brother 52 the girl wit...,4/27/2007,36.5950000,-82.2
6,10/10/1965 21:00,penarth (uk/wales),NaN,great britain,circle,180,about 3 mins,penarth uk circle 3mins stayed 30ft above m...,2/14/2006,51.434722,-3.2
7,10/10/1965 23:45,norwalk,ct,united states,disk,1200,20 minutes,A bright orange color changing to reddish colo...,10/2/1999,41.1175000,-73.4
8,10/10/1966 20:00,pell city,al,united states,disk,180,3 minutes,Strobe Lighted disk shape object observed clos...,3/19/2009,33.5861111,-86.3
9,10/10/1966 21:00,live oak,fl,united states,disk,120,several minutes,Saucer zaps energy from powerline as my pregna...,5/11/2005,30.2947222,-83.0