In [ ]:
import pandas as pd
pd.options.display.float_format = '{:.1f}'.format

In [ ]:
ufos_path = 'YOUR PATH HERE'

In [ ]:
ufo_sightings = pd.read_csv(ufos_path)
ufo_sightings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80332 entries, 0 to 80331
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              80332 non-null  object
 1   city                  80332 non-null  object
 2   state                 74535 non-null  object
 3   country               70662 non-null  object
 4   shape                 78400 non-null  object
 5   duration (seconds)    80332 non-null  object
 6   duration (hours/min)  80332 non-null  object
 7   comments              80317 non-null  object
 8   date posted           80332 non-null  object
 9   latitude              80332 non-null  object
 10  longitude             80332 non-null  float64
dtypes: float64(1), object(10)
memory usage: 6.7+ MB

<ipython-input-3-4e7438d38d9e>:1: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  ufo_sightings = pd.read_csv(ufos_path)

In [ ]:
no_nulls = ufo_sightings.dropna()
no_nulls.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66516 entries, 0 to 80331
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              66516 non-null  object
 1   city                  66516 non-null  object
 2   state                 66516 non-null  object
 3   country               66516 non-null  object
 4   shape                 66516 non-null  object
 5   duration (seconds)    66516 non-null  object
 6   duration (hours/min)  66516 non-null  object
 7   comments              66516 non-null  object
 8   date posted           66516 non-null  object
 9   latitude              66516 non-null  object
 10  longitude             66516 non-null  float64
dtypes: float64(1), object(10)
memory usage: 6.1+ MB

In [ ]:
only_all_nulls = ufo_sightings.dropna(how='all')
only_all_nulls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80332 entries, 0 to 80331
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              80332 non-null  object
 1   city                  80332 non-null  object
 2   state                 74535 non-null  object
 3   country               70662 non-null  object
 4   shape                 78400 non-null  object
 5   duration (seconds)    80332 non-null  object
 6   duration (hours/min)  80332 non-null  object
 7   comments              80317 non-null  object
 8   date posted           80332 non-null  object
 9   latitude              80332 non-null  object
 10  longitude             80332 non-null  float64
dtypes: float64(1), object(10)
memory usage: 6.7+ MB

In [ ]:
no_null_cols = ufo_sightings.dropna(axis=1)
no_null_cols.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80332 entries, 0 to 80331
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              80332 non-null  object
 1   city                  80332 non-null  object
 2   duration (seconds)    80332 non-null  object
 3   duration (hours/min)  80332 non-null  object
 4   date posted           80332 non-null  object
 5   latitude              80332 non-null  object
 6   longitude             80332 non-null  float64
dtypes: float64(1), object(6)
memory usage: 4.3+ MB

In [ ]:
no_null_shapes = ufo_sightings.dropna(subset='shape')
no_null_shapes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 78400 entries, 0 to 80331
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              78400 non-null  object
 1   city                  78400 non-null  object
 2   state                 72742 non-null  object
 3   country               69001 non-null  object
 4   shape                 78400 non-null  object
 5   duration (seconds)    78400 non-null  object
 6   duration (hours/min)  78400 non-null  object
 7   comments              78392 non-null  object
 8   date posted           78400 non-null  object
 9   latitude              78400 non-null  object
 10  longitude             78400 non-null  float64
dtypes: float64(1), object(10)
memory usage: 7.2+ MB

In [ ]:
ufo_sightings.dropna(subset='shape', inplace=True)
ufo_sightings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 78400 entries, 0 to 80331
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              78400 non-null  object
 1   city                  78400 non-null  object
 2   state                 72742 non-null  object
 3   country               69001 non-null  object
 4   shape                 78400 non-null  object
 5   duration (seconds)    78400 non-null  object
 6   duration (hours/min)  78400 non-null  object
 7   comments              78392 non-null  object
 8   date posted           78400 non-null  object
 9   latitude              78400 non-null  object
 10  longitude             78400 non-null  float64
dtypes: float64(1), object(10)
memory usage: 7.2+ MB

In [ ]:
ufo_sightings.loc[60:65]

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
60,10/10/1994 22:00,pinebergen,ar,us,light,5,5 seconds,Round&#44 bright&#44 low flying object silentl...,2/18/2001,34.1027778,-92.0
61,10/10/1994 23:00,toronto (greater toronto area) (canada),on,ca,sphere,3600,~1 hour,Large rusty sphere,7/3/2013,43.666667,-79.4
64,10/10/1996 03:20,higginsville,mo,us,triangle,3,3sec,illuminated triangular craft&#44 flying at hig...,2/16/2000,39.0725000,-93.7
65,10/10/1996 20:00,lake macquarie (nsw&#44 australia),NaN,NaN,light,300,5 min,RED LIGHT WITH OTHER RED FLASHING LIGHT&#44 ON...,5/24/1999,-33.093373,151.6

In [ ]:
ufo_sightings.reset_index(inplace=True)

In [ ]:
ufo_sightings.loc[60:65]

,index,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
60,60,10/10/1994 22:00,pinebergen,ar,us,light,5,5 seconds,Round&#44 bright&#44 low flying object silentl...,2/18/2001,34.1027778,-92.0
61,61,10/10/1994 23:00,toronto (greater toronto area) (canada),on,ca,sphere,3600,~1 hour,Large rusty sphere,7/3/2013,43.666667,-79.4
62,64,10/10/1996 03:20,higginsville,mo,us,triangle,3,3sec,illuminated triangular craft&#44 flying at hig...,2/16/2000,39.0725000,-93.7
63,65,10/10/1996 20:00,lake macquarie (nsw&#44 australia),NaN,NaN,light,300,5 min,RED LIGHT WITH OTHER RED FLASHING LIGHT&#44 ON...,5/24/1999,-33.093373,151.6
64,66,10/10/1996 22:00,charleston,sc,us,light,300,5 min,Flashing object above Charleston&#44 SC,11/26/2003,32.7763889,-79.9
65,67,10/10/1996 22:30,monroe county,oh,us,cylinder,60,1 minute,Looked like it went through the hillside,7/8/2004,39.4402778,-84.4