## Setup

In [ ]:
import pandas as pd

In [ ]:
ufos_path = 'YOUR PATH HERE'

In [ ]:
ufo_sightings = pd.read_csv(ufos_path)
ufo_sightings.head()

<ipython-input-3-87ccc3a49ac9>:1: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  ufo_sightings = pd.read_csv(ufos_path)

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611

## Add a "duration (minutes)" column to the DataFrame, immediately following the existing "duration (seconds)" column:

In [ ]:
ufo_sightings.insert(6, 'duration (minutes)', pd.to_numeric(ufo_sightings['duration (seconds)'], errors='coerce') / 60)

## Add a "distance from 37th" column, containing the difference between the latitude of a given sighting, and the 37th parallel:

In [ ]:
ufo_sightings['distance from 37th'] = abs(pd.to_numeric(ufo_sightings['latitude'], errors='coerce') - 37)

In [ ]:
ufo_sightings.head()

,datetime,city,state,country,shape,duration (seconds),duration (minutes),duration (hours/min),comments,date posted,latitude,longitude,distance from 37th
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45.000000,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111,7.116944
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,120.000000,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082,7.615790
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,0.333333,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667,16.200000
3,10/10/1956 21:00,edna,tx,us,circle,20,0.333333,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833,8.021667
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15.000000,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611,15.581944