## Setup

In [ ]:
import pandas as pd
pd.options.display.float_format = '{:.1f}'.format

In [ ]:
ufos_path = 'YOUR PATH HERE'
sightings = pd.read_csv(ufos_path)
sightings.head()

<ipython-input-3-828416dd11ab>:2: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  sightings = pd.read_csv(ufos_path)

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.9
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.6
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.9
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.6
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.8

## What is the highest latitude of a sighting identified with a "shape" of cylinder?

In [ ]:
sightings['latitude'] = pd.to_numeric(sightings['latitude'], errors='coerce')

In [ ]:
cylinders = sightings[sightings['shape'] == 'cylinder']
cylinders['latitude'].max()

71.3875

**71.3875 degrees**

## How does the average duration of sightings in the United States compare to the median duration of sightings in Australia?

In [ ]:
sightings['duration (minutes)'] = pd.to_numeric(sightings['duration (seconds)'], errors='coerce') / 60

In [ ]:
us_sightings = sightings[sightings['country'] == 'us']
us_sightings['duration (minutes)'].mean()

96.66986747962486

In [ ]:
au_sightings = sightings[sightings['country'] == 'au']
au_sightings['duration (minutes)'].mean()

63.441153965303585

**Average duration of sightings in US: 96.67 minutes**

**Average duration of sightings in Australia: 63.44 minutes**

## Which city in the US state of California had the most sightings?

In [ ]:
ca_sightings = sightings[sightings['state'] == 'ca']
ca_sightings.describe(include='all')

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude,duration (minutes)
count,9655,9655,9655,8912,9405,9655,9655,9654,9655,9655.0,9655.0,9654.0
unique,9280,1806,1,1,23,259,1866,9642,306,NaN,NaN,NaN
top,9/1/1999 21:30,los angeles,ca,us,light,300,5 minutes,Orange ball of light.,10/30/2006,NaN,NaN,NaN
freq,12,352,9655,8912,1983,881,573,3,186,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.8,-119.4,65.5
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5,3.1,2261.6
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-28.5,-124.5,0.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.9,-121.7,0.5
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.5,-118.8,3.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.8,-117.9,10.0
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.9,-6.2,175440.0

**Los Angeles**