## Setup

In [ ]:
import pandas as pd
pd.options.display.float_format = '{:.1f}'.format

In [ ]:
ufos_path = 'YOUR PATH HERE'
sightings = pd.read_csv(ufos_path)
sightings.head()

<ipython-input-2-828416dd11ab>:2: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  sightings = pd.read_csv(ufos_path)

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.9
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.6
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.9
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.6
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.8

## How does the average duration of sightings in the United States compare to the average duration of sightings everywhere else?

In [ ]:
sightings['duration (seconds)'] = pd.to_numeric(sightings['duration (seconds)'], errors='coerce')

In [ ]:
us_sightings = sightings[sightings['country'] == 'us']
us_sightings['duration (seconds)'].mean() / 60

96.66986747962484

In [ ]:
non_us_sightings = sightings[sightings['country'] != 'us']
non_us_sightings['duration (seconds)'].mean() / 60

379.70976898753594

**Average duration of US sightings: 96.7 minutes**

**Average duration of non-US sightings: 379.7 minutes**

## What is the most common/frequent sighting "shape" among sightings above 66.5 degrees latitude?

In [ ]:
sightings['latitude'] = pd.to_numeric(sightings['latitude'], errors='coerce')

In [ ]:
arctic_sightings = sightings[sightings['latitude'] > 66.5]
arctic_sightings.describe(include='all')

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
count,18,18,12,7,17,18.0,18,18,18,18.0,18.0
unique,17,15,2,2,7,NaN,18,18,17,NaN,NaN
top,8/13/2007 00:45,tromsoe (norway),ak,us,light,NaN,10-15min,Radar sighting and filming,10/8/2007,NaN,NaN
freq,2,3,8,4,6,NaN,1,1,2,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,498.8,NaN,NaN,NaN,69.7,-86.4
std,NaN,NaN,NaN,NaN,NaN,724.1,NaN,NaN,NaN,1.8,79.3
min,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,66.9,-162.6
25%,NaN,NaN,NaN,NaN,NaN,45.0,NaN,NaN,NaN,67.9,-154.6
50%,NaN,NaN,NaN,NaN,NaN,240.0,NaN,NaN,NaN,69.8,-134.0
75%,NaN,NaN,NaN,NaN,NaN,750.0,NaN,NaN,NaN,70.6,15.2
max,NaN,NaN,NaN,NaN,NaN,2700.0,NaN,NaN,NaN,72.7,19.0

**light**

## What is the median latitude among sightings less than or equal to 10 seconds in duration?

In [ ]:
short_sightings = sightings[sightings['duration (seconds)'] <= 10]
short_sightings['latitude'].median()

39.46438585

**39.5 degrees**