## Setup

In [ ]:
import pandas as pd

In [ ]:
ufos_path = 'YOUR PATH HERE'
sightings = pd.read_csv(ufos_path)
sightings.head()

<ipython-input-14-828416dd11ab>:2: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  sightings = pd.read_csv(ufos_path)

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611

## Fetch all records with a null "shape" value in the UFO sightings dataset, into their own distinct DataFrame:

In [ ]:
null_shapes = sightings[sightings['shape'].isna()]
null_shapes.head()

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
62,10/10/1995 19:45,milwaukee,wi,us,NaN,120,2 min.,Man on Hwy 43 SW of Milwaukee sees large&#44 ...,11/2/1999,43.0388889,-87.906389
63,10/10/1995 22:40,oakland,ca,us,NaN,60,1 minute,Woman repts. bright light in NW sky&#44 sudde...,11/2/1999,37.8044444,-122.269722
239,10/10/2011 19:30,murfeesboro/smyrna,tn,NaN,NaN,2700,30-45 minutes,Multi color oblect over Smyrna/Murfreesboro 10...,10/19/2011,35.947474,-86.488367
285,10/11/1986 20:30,alice springs (nt&#44 australia),NaN,au,NaN,20,20 seconds,Being of light reported&#44Jesus or another m...,1/19/2005,-23.697479,133.883621
293,10/11/1995 18:30,new york city (brooklyn),ny,us,NaN,720,12 min.,Young man&#44 mother witness watch strange red...,11/2/1999,40.7141667,-74.006389

## What is the most frequently occurring "state" among those sightings with a null "shape"?

In [ ]:
null_shapes.describe(include='all')

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
count,1932,1932,1793,1661,0,1932,1932,1925,1932,1932,1932.000000
unique,1880,1330,62,5,0,141,496,1924,264,1418,NaN
top,10/14/1995 22:30,seattle,wa,us,NaN,300,1 minute,Two red lights in the sky,11/2/1999,47.6063889,NaN
freq,5,52,279,1553,NaN,143,71,2,764,50,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-92.450972
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.259994
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-163.729444
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-120.191738
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95.018333
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-80.270278
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178.000000

**"wa" (Washington)**

## Identify any values in the "latitude" column of the UFO sightings dataset that can't be converted to numbers:

In [ ]:
null_latitudes = pd.to_numeric(sightings['latitude'], errors='coerce').isna()

sightings[null_latitudes]['latitude']

43782    33q.200088
Name: latitude, dtype: object

**33q.200088**

## How many values in the "datetime" columns of the UFO sightings dataset can't be converted to dates?

In [ ]:
null_datetimes = pd.to_datetime(sightings['datetime'], errors='coerce').isna()

len(sightings[null_datetimes])

694

**694**