## Setup

In [ ]:
import pandas as pd

## Programatically calculate the number of values in the "datetime" column of the UFO sightings dataset that can't be converted to actual datetimes:

In [ ]:
ufos_path = 'YOUR PATH HERE'
ufo_sightings = pd.read_csv(ufos_path)

<ipython-input-3-60ea0c9e0214>:2: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  ufo_sightings = pd.read_csv(ufos_path)

## Use `iloc` to fetch row the 27,823rd row of the UFO sightings dataset into a Series and preview it:

In [ ]:
ufo_sightings.iloc[27822]

datetime                                                   2/2/2000 19:33
city                                                                bouse
state                                                                  az
country                                                                us
shape                                                                 NaN
duration (seconds)                                                     2`
duration (hours/min)                                   each a few seconds
comments                Driving through Plomosa Pass towards Bouse Loo...
date posted                                                     2/16/2000
latitude                                                       33.9325000
longitude                                                        -114.005
Name: 27822, dtype: object

## Which value in the row looks like it might cause a conversion error if its parent column is converted to a numeric data type?

**The "2`" in the "duration (seconds)" column (note the backtick after the 2)**

## Use `iloc` to fetch row the 43,783rd row of the UFO sightings dataset into a Series and preview it.

In [ ]:
ufo_sightings.iloc[43782]

datetime                                                  5/22/1974 05:30
city                                         mescalero indian reservation
state                                                                  nm
country                                                               NaN
shape                                                           rectangle
duration (seconds)                                                    180
duration (hours/min)                                            two hours
comments                Huge rectangular object emmitting intense whit...
date posted                                                     4/18/2012
latitude                                                       33q.200088
longitude                                                     -105.624152
Name: 43782, dtype: object

## Which value in the row looks like it might cause a conversion error if its parent column is converted to a numeric data type?

**The "33q.200088" in the "latitude" column (note the "q" mixed in with the numeric digits)**

## Use `iloc` to select rows the 27,823rd AND 43,783rd rows - and ONLY the "duration (seconds)" and "latitude" columns - into a DataFrame:

In [ ]:
ufo_sightings.iloc[[27822, 43782], [5, 9]]

      duration (seconds)    latitude
27822                 2`  33.9325000
43782                180  33q.200088

## Use `iloc` to fetch rows 50000 through 59999 into a DataFrame. Assign the DataFrame to a variable.

In [ ]:
slice = ufo_sightings.iloc[49999:59999]

## Apply the `describe` method to the resulting DataFrame, including all data types:

In [ ]:
slice.describe(include='all')

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
count,10000,10000,9264,8751,9808,10000,10000,9998,10000,10000,10000.000000
unique,8633,5071,65,5,23,202,1989,9986,304,5217,NaN
top,7/15/2001 00:30,seattle,ca,us,light,300,5 minutes,((NUFORC Note: No information provided by wit...,8/5/2009,40.7141667,NaN
freq,11,64,1131,7912,2130,1065,597,3,455,79,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-86.327850
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.710836
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-166.360833
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-112.013194
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.650000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-78.225833
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176.912018

## How many missing/NaN values are in the "state" and "shape" columns, respectively, for this slice of the DataFrame?

**736 and 192, respectively**